### PR TITLE
a mistake about smash products of EM spectra

### PR DESCRIPTION
**Pull request by HanaJiaKong**

### CODE REVIEW

**Comment by ajblumberg** [comment]
This was a typo; it should have said lax symmetric monoidal.  Then H is lax non-equivariantly but cannot be lax equivariantly (e.g., see work of Ullman).  I'd prefer not to lose that thought, although it's also fine to point out that the functor is never strong.

**Comment by HanaJiaKong** [comment]
Thank you for the reply! That makes sense. I will make a new pull request.

> This was a typo; it should have said lax symmetric monoidal. Then H is lax non-equivariantly but cannot be lax equivariantly (e.g., see work of Ullman). I'd prefer not to lose that thought, although it's also fine to point out that the functor is never strong.

**Comment by HanaJiaKong** [comment]
I've edited the typo and added the reference. Could you please review it? Thank you!

**Comment by ajblumberg** [comment]
Looks good to me.  Thanks for taking care of this!

**Comment by adebray** [comment]
looks good to me as well. thanks for fixing this!

**Pull request merged**
